/**
 * Contract templates (ADR-0007): FR/AR (MVP) + EN. Structured label dictionaries —
 * the content is data; this renders it. Default clauses reflect common Moroccan agency
 * practice (research register #23/#24/#25: industry practice, NOT legal advice).
 */
export type Lang = 'fr' | 'ar' | 'en';

export const T = {
  fr: {
    title: 'CONTRAT DE LOCATION DE VOITURE SANS CHAUFFEUR',
    parties: 'LOCATAIRE', agency: 'Loueur', cin: 'CIN / Passeport', license: 'Permis de conduire',
    licenseIssued: 'Permis délivré le', phone: 'Téléphone', address: 'Adresse', birthDate: 'Date de naissance',
    vehicleSection: 'VÉHICULE', plate: 'Immatriculation', makeModel: 'Marque / Modèle', category: 'Catégorie',
    vin: 'N° de châssis (VIN)', mileageOut: 'Kilométrage au départ', fuelOut: 'Carburant au départ',
    periodSection: 'DURÉE', pickupAt: 'Départ le', returnAt: 'Retour le', days: 'Nombre de jours',
    pickupBranch: 'Agence de départ', returnBranch: 'Agence de retour',
    pricingSection: 'TARIF', dailyRate: 'Tarif journalier', discount: 'Remise', total: 'TOTAL',
    depositSection: 'CAUTION (DÉPÔT DE GARANTIE)', depositAmount: 'Montant', depositMethod: 'Mode', heldAt: 'Consignée le',
    insuranceSection: 'ASSURANCE ET FRANCHISE', franchise: 'Franchise', cdw: 'Rachat partiel de dommages (CDW)',
    superCdw: 'Super CDW (franchise zéro)', exclusions: 'Exclusions', exclusionsList: ['Pneumatiques', 'Glace pare-brise', 'Sous-bassement', 'Intérieur'],
    crossBorderSection: 'AUTORISATION DE SORTIE DU TERRITOIRE',
    crossBorderNote: 'Interdiction absolue de sortie vers Ceuta et Melilla et d’embarquement Tanger Med sans autorisation écrite et Admission Temporaire (AT).',
    authorized: 'Autorisé', zones: 'Zones', atRef: 'Référence AT',
    mileageFuelSection: 'KM & CARBURANT', mileageIn: 'Kilométrage au retour', fuelIn: 'Carburant au retour',
    includedKm: 'KM inclus / jour', extraKmRate: 'Tarif KM supplémentaire',
    driversSection: 'CONDUCTEURS ADDITIONNELS', driverName: 'Nom', driverLicense: 'Permis', driverBirth: 'Né(e) le',
    consentsSection: 'CONSENTEMENTS (CNDP — Loi 09-08)',
    consentGps: 'Géolocalisation du véhicule pendant la location (protection du patrimoine)',
    consentMarketing: 'Communications commercielles', consentData: 'Traitement des données personnelles',
    signatureSection: 'SIGNATURES', customerSig: 'Signature du locataire', agentSig: 'Signature de l’agent',
    at: 'Le', ref: 'N° de contrat', blankNote: 'CONTRAT VIERGE — à compléter à la main. Numéro réservé et traçable.',
    page: 'Page 1',
    clauses: [
      'Le locataire déclare avoir reçu le véhicule en bon état de marche et s’engage à le restituer dans le même état.',
      'Le véhicule est loué avec assurance responsabilité civile obligatoire; les dommages au véhicule restent à la charge du locataire dans la limite de la franchise, sauf rachat (CDW / Super CDW).',
      'Tout dépassement du forfait kilométrique est facturé au tarif indiqué ci-dessus.',
      'Le véhicule ne peut circuler hors du territoire marocain sans autorisation écrite préalable (AT douane).',
      'La caution est restituée après restitution du véhicule, contrôle des dommages et vérification des amendes (infractions NARSA/ANSR).',
    ],
  },
  ar: {
    title: 'عقد كراء سيارة بدون سائق',
    parties: 'المستأجر', agency: 'المؤجر', cin: 'البطاقة الوطنية / جواز السفر', license: 'رخصة السياقة',
    licenseIssued: 'تاريخ تسليم الرخصة', phone: 'الهاتف', address: 'العنوان', birthDate: 'تاريخ الميلاد',
    vehicleSection: 'السيارة', plate: 'رقم اللوحة', makeModel: 'الماركة / الطراز', category: 'الفئة',
    vin: 'رقم الهيكل (VIN)', mileageOut: 'عدد الكيلومترات عند المغادرة', fuelOut: 'الوقود عند المغادرة',
    periodSection: 'مدة الكراء', pickupAt: 'المغادرة في', returnAt: 'العودة في', days: 'عدد الأيام',
    pickupBranch: 'وكالة المغادرة', returnBranch: 'وكالة العودة',
    pricingSection: 'التعرفة', dailyRate: 'التعرفة اليومية', discount: 'تخفيض', total: 'المجموع',
    depositSection: 'الكفالة (الطيان)', depositAmount: 'المبلغ', depositMethod: 'طريقة الأداء', heldAt: 'تاريخ الاحتفاظ',
    insuranceSection: 'التأمين والتحمل', franchise: 'التحمل (الفرانشيز)', cdw: 'تخفيف التحمل (CDW)',
    superCdw: 'التحمل الصفري (Super CDW)', exclusions: 'الاستثناءات', exclusionsList: ['العجلات', 'الزجاج الأمامي', 'أسفل السيارة', 'المقصورة'],
    crossBorderSection: 'الترخيص بالخروج من التراب الوطني',
    crossBorderNote: 'يمنع منعاً كلياً التوجه نحو سبتة ومليلية أو عبور طنجة المتوسط دون إذن كتابي مسبق وقبول مؤقت (AT).',
    authorized: 'مرخص', zones: 'المناطق', atRef: 'مرجع القبول المؤقت',
    mileageFuelSection: 'الكيلومتراژ والوقود', mileageIn: 'عدد الكيلومترات عند العودة', fuelIn: 'الوقود عند العودة',
    includedKm: 'الكيلومتراژ المشمول يومياً', extraKmRate: 'تعرفة الكيلومتر الإضافي',
    driversSection: 'السائقون الإضافيون', driverName: 'الاسم', driverLicense: 'الرخصة', driverBirth: 'تاريخ الميلاد',
    consentsSection: 'الموافقات (اللجنة الوطنية لمراقبة حماية المعطيات — القانون 09.08)',
    consentGps: 'تتبع موقع السيارة أثناء الكراء (حماية الممتلكات)',
    consentMarketing: 'الرسائل التجارية', consentData: 'معالجة المعطيات الشخصية',
    signatureSection: 'التوقيعات', customerSig: 'توقيع المستأجر', agentSig: 'توقيع الوكيل',
    at: 'في', ref: 'رقم العقد', blankNote: 'عقد فارغ — يُملأ بخط اليد. الرقم محفوظ وقابل للتتبع.',
    page: 'صفحة 1',
    clauses: [
      'يقر المستأجر بأنه تسلم السيارة في حالة سليمة ويتعهد بإرجاعها في نفس الحالة.',
      'السيارة مؤمنة بالمسؤولية المدنية الإجبارية؛ تبقى الأضرار اللحقة بالسيارة على عاتق المستأجر في حدود التحمل ما لم يتم Rachat (CDW / Super CDW).',
      'يُحتسب كل تجاوز للحصة اليومية من الكيلومتراژ بالتعرفة المذكورة أعلاه.',
      'لا يجوز للسيارة الخروج من التراب الوطني دون ترخيص كتابي مسبق (AT).',
      'تُرجع الكفالة بعد إرجاع السيارة ومراقبة الأضرار والتحقق من المخالفات (NARSA/ANSR).',
    ],
  },
  en: {
    title: 'VEHICLE RENTAL AGREEMENT (SELF-DRIVE)',
    parties: 'RENTER', agency: 'Rental company', cin: 'ID card / Passport', license: 'Driving licence',
    licenseIssued: 'Licence issued on', phone: 'Phone', address: 'Address', birthDate: 'Date of birth',
    vehicleSection: 'VEHICLE', plate: 'Registration', makeModel: 'Make / Model', category: 'Category',
    vin: 'Chassis No. (VIN)', mileageOut: 'Mileage at departure', fuelOut: 'Fuel at departure',
    periodSection: 'PERIOD', pickupAt: 'Pick-up', returnAt: 'Return', days: 'Days',
    pickupBranch: 'Pick-up branch', returnBranch: 'Return branch',
    pricingSection: 'RATE', dailyRate: 'Daily rate', discount: 'Discount', total: 'TOTAL',
    depositSection: 'SECURITY DEPOSIT (CAUTION)', depositAmount: 'Amount', depositMethod: 'Method', heldAt: 'Held on',
    insuranceSection: 'INSURANCE & DEDUCTIBLE', franchise: 'Deductible', cdw: 'CDW', superCdw: 'Super CDW (zero deductible)',
    exclusions: 'Exclusions', exclusionsList: ['Tyres', 'Windscreen', 'Undercarriage', 'Interior'],
    crossBorderSection: 'CROSS-BORDER AUTHORISATION',
    crossBorderNote: 'Strictly forbidden to enter Ceuta/Melilla or board the Tanger Med ferry without written authorisation and Temporary Admission (AT).',
    authorized: 'Authorised', zones: 'Zones', atRef: 'AT reference',
    mileageFuelSection: 'KM & FUEL', mileageIn: 'Mileage at return', fuelIn: 'Fuel at return',
    includedKm: 'Included km / day', extraKmRate: 'Extra km rate',
    driversSection: 'ADDITIONAL DRIVERS', driverName: 'Name', driverLicense: 'Licence', driverBirth: 'Born on',
    consentsSection: 'CONSENTS (CNDP — Law 09-08)',
    consentGps: 'Vehicle geolocation during the rental (asset protection)',
    consentMarketing: 'Commercial communications', consentData: 'Personal data processing',
    signatureSection: 'SIGNATURES', customerSig: 'Renter’s signature', agentSig: 'Agent’s signature',
    at: 'On', ref: 'Contract No.', blankNote: 'BLANK CONTRACT — to be completed by hand. Number reserved and traceable.',
    page: 'Page 1',
    clauses: [
      'The renter confirms receiving the vehicle in good working condition and agrees to return it in the same condition.',
      'The vehicle includes mandatory third-party liability; damage remains chargeable up to the deductible unless waived (CDW / Super CDW).',
      'Mileage beyond the daily allowance is billed at the rate stated above.',
      'The vehicle may not leave Moroccan territory without prior written authorisation (customs AT).',
      'The deposit is returned after vehicle return, damage inspection and fine verification (NARSA/ANSR).',
    ],
  },
} as const;
